"""ESP32/TFLite Micro deployment bundle generation."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import tensorflow as tf


def export_input_quantization_header(
    tflite_path: str | Path,
    out_h_path: str | Path,
    amplitude_range: float,
) -> Path:
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    input_detail = interpreter.get_input_details()[0]
    scale, zero_point = input_detail["quantization"]

    if input_detail["dtype"] != np.int8 or scale <= 0:
        raise ValueError(
            "Expected an int8 TFLite input with a positive quantization scale."
        )
    if not np.isfinite(amplitude_range) or amplitude_range <= 0:
        raise ValueError("Input amplitude range must be positive and finite.")

    out_h_path = Path(out_h_path)
    out_h_path.parent.mkdir(parents=True, exist_ok=True)
    out_h_path.write_text(
        "#pragma once\n\n"
        "// Generated from the quantized TFLite model.\n"
        f"#define MODEL_INPUT_SCALE {scale:.10g}f\n"
        f"#define MODEL_INPUT_ZERO_POINT {zero_point}\n"
        f"#define MODEL_INPUT_AMPLITUDE_RANGE {amplitude_range:.10g}f\n",
        encoding="utf-8",
    )
    print(f"Exported input quantization header: {out_h_path}")
    return out_h_path


def export_ota_config_json(
    tflite_path: str | Path,
    out_json_path: str | Path,
    amplitude_range: float = 0.03,
    sample_rate: int = 8000,
    segment_length: int = 2400,
    detection_threshold: float = 0.60,
    class_names: Sequence[str] | None = None,
    dc_removal: bool = True,
    high_pass_filter: bool = True,
    high_pass_cutoff_hz: float = 150.0,
    pre_emphasis: bool = False,
    pre_emphasis_coeff: float = 0.97,
    rms_normalization: bool = True,
) -> Path:
    import json
    import time

    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    input_detail = interpreter.get_input_details()[0]
    scale, zero_point = input_detail["quantization"]

    out_json_path = Path(out_json_path)
    out_json_path.parent.mkdir(parents=True, exist_ok=True)

    config_data = {
        "model_version": time.strftime("%Y%m%d_%H%M%S"),
        "audio": {
            "sample_rate": sample_rate,
            "segment_length": segment_length,
            "amplitude_range": amplitude_range,
            "hop_length_ms": 150,
        },
        "preprocessing_overrides": {
            "dc_removal": dc_removal,
            "high_pass_filter": high_pass_filter,
            "high_pass_cutoff_hz": high_pass_cutoff_hz,
            "pre_emphasis": pre_emphasis,
            "pre_emphasis_coeff": pre_emphasis_coeff,
            "rms_normalization": rms_normalization,
            "target_rms": amplitude_range,
        },
        "quantization": {
            "input_scale": float(scale),
            "input_zero_point": int(zero_point),
        },
        "inference": {
            "detection_threshold": detection_threshold,
            "min_frequency_hz": 150.0,
            "max_frequency_hz": 1500.0,
        },
        "classes": list(class_names) if class_names else [],
    }

    out_json_path.write_text(json.dumps(config_data, indent=2), encoding="utf-8")
    print(f"Exported OTA config JSON: {out_json_path}")
    return out_json_path


def export_tflite_to_c_header(
    tflite_path: str | Path,
    out_h_path: str | Path,
    array_name: str = "g_model",
) -> Path:
    """
    Exports TFLite model bytes to a C/C++ header file containing a byte array.
    This is required for ESP32/TFLite Micro deployment where the model is compiled into the binary.
    """
    tflite_path = Path(tflite_path)
    out_h_path = Path(out_h_path)
    out_h_path.parent.mkdir(parents=True, exist_ok=True)

    model_bytes = tflite_path.read_bytes()
    num_bytes = len(model_bytes)

    lines = [
        "// This file is automatically generated. Do not modify.",
        f"#ifndef {array_name.upper()}_H",
        f"#define {array_name.upper()}_H",
        "",
        "// Align to 16 bytes for alignment requirements of TFLite Micro interpreter",
        "#if defined(__GNUC__) || defined(__clang__)",
        "  #define TFLITE_ALIGN __attribute__((aligned(16)))",
        "#else",
        "  #define TFLITE_ALIGN alignas(16)",
        "#endif",
        "",
        f"const unsigned int {array_name}_len = {num_bytes};",
        f"const unsigned char {array_name}[] TFLITE_ALIGN = {{",
    ]

    # Format bytes in chunks of 12 per line for readability
    chunk_size = 12
    for i in range(0, num_bytes, chunk_size):
        chunk = model_bytes[i:i + chunk_size]
        hex_strs = [f"0x{b:02x}" for b in chunk]
        line = "    " + ", ".join(hex_strs)
        if i + chunk_size < num_bytes:
            line += ","
        lines.append(line)

    lines.extend([
        "};",
        "",
        "#endif // " + f"{array_name.upper()}_H",
    ])

    out_h_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Exported C header: {out_h_path} ({num_bytes} bytes)")
    return out_h_path


def write_esp32_readme(out_dir: Path, array_name: str = "g_model") -> Path:
    readme_path = out_dir / "README_ESP32.md"
    content = f"""# ESP32 TFLite Micro Deployment Guide

This directory contains the quantized TFLite model and the corresponding C/C++ header array ready to be compiled directly into your ESP-IDF or Arduino project.

## Files Generated
- `model_full_int8.tflite`: Full integer quantized model.
- `model_full_int8.h`: C++ header file containing the model as a byte array (`{array_name}`).
- `quantization_summary.csv`: Evaluation metrics comparing Keras float, TFLite float, dynamic range, and full int8.
- `model_full_int8_analyzer.txt`: Detail layer-by-layer structure and execution profiles.

## C++ ESP32 Integration Example

To run inference on your ESP32-S3 or other compatible microcontroller, use the following template:

```cpp
#include "model_full_int8.h"
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Adjust tensor arena size as needed based on model complexity (e.g. 60-120 KB)
constexpr int kTensorArenaSize = 100 * 1024;
// Allocate in fast internal SRAM (DRAM), NOT external PSRAM, for 3x memory speed
alignas(16) DRAM_ATTR uint8_t tensor_arena[kTensorArenaSize];

const tflite::Model* model = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input = nullptr;
TfLiteTensor* output = nullptr;

void setup() {{
    // 1. Initialize TFLite model from header array
    model = tflite::GetModel({array_name});
    if (model->version() != TFLITE_SCHEMA_VERSION) {{
        return;
    }}

    // 2. Optimized Op Resolver (Use MicroMutableOpResolver<5> for minimal RAM & flash)
    static tflite::MicroMutableOpResolver<5> resolver;
    resolver.AddConv2D();
    resolver.AddMaxPool2D();
    resolver.AddReshape();
    resolver.AddFullyConnected();
    resolver.AddSoftmax();

    // 3. Instantiate interpreter
    static tflite::MicroInterpreter static_interpreter(
        model, resolver, tensor_arena, kTensorArenaSize
    );
    interpreter = &static_interpreter;

    // 4. Allocate tensors
    if (interpreter->AllocateTensors() != kTfLiteOk) {{
        // Handle allocation failure
        return;
    }}

    // 5. Cache input/output tensor pointers
    input = interpreter->input(0);
    output = interpreter->output(0);
}}

void loop() {{
    // Fill input->data.int8 with quantized input values:
    // For raw input x (float):
    // input->data.int8[i] = (int8_t)round(x[i] / input->params.scale + input->params.zero_point);

    // Run inference
    TfLiteStatus invoke_status = interpreter->Invoke();
    if (invoke_status != kTfLiteOk) {{
        // Handle invocation failure
        return;
    }}

    // Read output->data.int8:
    // Dequantize output if you need float scores:
    // float score = (output->data.int8[class_idx] - output->params.zero_point) * output->params.scale;
}}
```
"""
    readme_path.write_text(content.strip() + "\n", encoding="utf-8")
    print(f"Created ESP32 deployment instructions: {readme_path}")
    return readme_path
