model:
    mossongplus:
        conv:
            - filters: 32
              kernel_size: 100
              strides: 4
              activation: relu
              padding: valid
              batch_norm: true

            - filters: 32
              kernel_size: 64
              strides: 4
              activation: relu
              padding: valid
              batch_norm: true

            - filters: 64
              kernel_size: 64
              strides: 3
              activation: relu
              padding: valid
              batch_norm: true

        maxpool:
            - pool_size: 3
              strides: 3
              padding: valid

        flatten: true
        # global_avg_pool: true
        # global_max_pool: true

        dropout:
            - rate: 0.5

        dense:
            - units: 256
              activation: relu

            - units: 128
              activation: relu

    flatten: true
