model:
  mosssongplus:
    conv:
      - filters: 32
        kernel_size: 100
        strides: 4
        activation: relu
      - filters: 32
        kernel_size: 64
        strides: 4
        activation: relu
      - filters: 32
        kernel_size: 64
        strides: 3
        activation: relu
    pooling: 3
    dropout: 0.5
    dense:
      - units: 256
        activation: relu
      - units: 128
        activation: relu
